name: "Please Star Light"
author: "qxip"
description: "Automatically comments issues opened by non-stargazers"
branding:
  icon: star
  color: yellow
inputs:
  token:
    description: "GitHub token for use by this action."
    required: false
    default: ${{ github.token }}
  message:
    description: "Message"
    required: false
    default: |
      Please star this repository to motivate developers.

      Thanks!
runs:
  using: "node12"
  main: "dist/index.js"
